# Generated by Django 4.1.7 on 2023-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurements_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
